[workspace]
members = ["program", "protocol", "reactive", "server", "task"]
exclude = ["samples"]
resolver = "2"

[workspace.dependencies]
protocol = { path = "protocol" }
reactive = { path = "reactive" }
task = { path = "task"}
