[package]
name = "protocol"
version = "0.1.0"
authors = ["Sieluna <seele.peng@gmail.com>"]
edition = "2021"
resolver = "2"

[dependencies]
bincode = { version = "2.0.0-rc", default-features = false, features = ["derive", "alloc"] }
thiserror = { version = "2", default-features = false }
