[package]
name = "server"
version = "0.1.0"
authors = ["Sieluna <seele.peng@gmail.com>"]
edition = "2021"
resolver = "2"

[dependencies]
bitvec = "1"
bytes = "1"
env_logger = "0.11"
hecs = "0.10"
log = "0.4"
protocol.workspace = true
tokio = { version = "1", features = ["full"] }
